version: 0.1

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - rm -r target/*
      - mkdir -p target/stage
      - mkdir target/prod
      - serverless package --package target/stage --stage stage -v -r ap-south-1
      - serverless package --package target/prod --stage prod -v -r ap-south-1


artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
